export type PageRow = {
  locale: string;
  pathKey: string;
  mirrorPathKey: string | null;
  file: string;
  urlPath: string;
  mtimeMs: number | null;
};

/** GitHub target for “open in repo” links (letters-website). */
export type SiteRepository = {
  owner: string;
  name: string;
  defaultBranch: string;
};

export type PagesManifest = {
  generatedAt: string;
  baseUrl: string;
  /** Relative path from the backoffice package to the scanned marketing tree (standalone builds). */
  sourceRoot?: string;
  /** Present in manifests generated by current scripts; older JSON may omit. */
  siteRepository?: SiteRepository;
  /** How routes were discovered. */
  manifestSource?: "html" | "next-app";
  prefixLocales: string[];
  legacyRoots: Record<string, string>;
  pages: PageRow[];
};

export type ComponentPattern = {
  id: string;
  file: string;
  category: string | null;
};

export type ComponentInventory = {
  generatedAt: string;
  sourceRoot?: string;
  siteRepository?: SiteRepository;
  components: ComponentPattern[];
};

export type OpportunityItem = {
  id: string;
  title: string;
  source: "gsc" | "ga4" | "ahrefs" | "semrush" | "manual" | "other";
  /** Primary URL path on letters.game, starting with / */
  urlPath: string;
  locale?: string;
  metricHint?: string;
  priority?: "high" | "medium" | "low";
  notes?: string;
};

export type OpportunitiesDoc = {
  generatedAt: string;
  items: OpportunityItem[];
};

export type CoverageScoring = {
  staleDays: number;
  penalties: { field: number; stale: number };
  notes?: string;
};

export type CoverageRow = {
  mirrorPathKey: string;
  enUrlPath: string;
  enFile: string;
  avg: number;
  scores: Record<string, number | null>;
};

export type CoverageSnapshot = {
  generatedAt: string;
  baseUrl: string;
  siteRepository?: SiteRepository | null;
  sourceRoot?: string;
  locales: string[];
  scoring: CoverageScoring;
  rows: CoverageRow[];
};
